### ISSUE TITLE
[task] jenkins application  설치 

### ISSUE THREAD

**Issue by headcha** [Kwangpyo/Volunteer-Matching#14]
1. ci 서버에 java 를 설치한다 ( openjdk 는 사용하지 않는다 ) 
2. java 는 oracle 8 최신 버전을 설치 한다. 
3. jenkins 는 최신 버전을 설치 한다. 
4. jenkins 의  기본 포트는 9001 을 이용한다.

**Comment by soyoung6488** [comment]
java 설치 완료

**Comment by soyoung6488** [comment]
jenkins 설치 및 포트 설정 완료

**Comment by soyoung6488** [comment]
![image](https://user-images.githubusercontent.com/22609946/39295150-9ffa0104-4978-11e8-99da-471b764782af.png)
사진에 있는 기본 추천 plugin 설치함

**Comment by soyoung6488** [comment]
Admin 계정: volma
PW: volma!1team@2
로 설정해둠

**Comment by headcha** [comment]
와우 쵝오~! 접속 할 수 있는 IP 도 알려주세요

**Comment by soyoung6488** [comment]
http://49.236.137.89:9001 입니다
slack에 등록해놨습니다
