### ISSUE TITLE
[Task] node.js application 설치

### ISSUE THREAD

**Issue by headcha** [Kwangpyo/Volunteer-Matching#16]
1. was 서버에 node.js 를 설치한다 
2. 9001 port 를 이용한다.
3. nginx 설치 및 실행 계정은  suser 를 이용한다
4. 설치후 http://ip:9001 로 접속할 수 있어야 한다.

**Comment by soyoung6488** [comment]
1, 2, 3(실행 및 설치는 어쩔수없이 root로 진행함) 완료
4. http://45.119.146.26:9001로 접속 가능

**Comment by headcha** [comment]
으잉??? node.js 인데 왜..nginx 페이지가?

**Comment by headcha** [comment]
이슈는 리오픈 합니다. nginx 가 설치된것 같아요

**Comment by soyoung6488** [comment]
엇 그거 설치하는거 아닌가요

**Comment by soyoung6488** [comment]
음 node를 9001에 띄우는건데 제가 nginx를 넣은건가요 
다시 해보겠습니다

**Comment by soyoung6488** [comment]
다시 완료했습니다.
