### ISSUE TITLE
[이슈] 개발 서버 구축

### ISSUE THREAD

**Issue by headcha** [Kwangpyo/Volunteer-Matching#7]
Project  진행함에 있어 결과물을 즉시 볼 수 있는 개발 서버 구축이 필요합니다. 
기술 스택 협의 이후 협의 결과에 따라 구축하면 될것 같고요.

AWS 를 이용하는 것도 좋으나 지금 시점에서는 서버를 날것으로 다뤄보는 기술도 필요하다 생각 됩니다.

따라서 AWS 는 상용 ( 런칭 ) 으로 두고 개발 하면서 사용할 서버는 AWS 가 아닌 다른 플랫폼 ( 가상 서버 호스팅 ) 을 이용해 보는 것이 좋을 것 같아요.

어느 정도 비용이 발생할 수 있으니 ( 월 1만원 +a ) 잘 협의해서 의견 주세요.

결정되면 적당한 플랫폼은 저도 찾아 볼께요.

**Comment by junmin-p** [comment]
Conoha 회원가입하다가 2천원 날라갔어요..ㅠㅠ
다른 호스팅 사이트 찾아볼까요..?

**Comment by headcha** [comment]
코노하 로그인 어렵다는 의견이 있어서
네이버 클라우드 플랫폼 살펴보니
괜찮을것 같아요~
마이크로 서버는 1년 무료로 주고 있으니
마이크로 서버를 ci 서버로 사용하고
was 1대 db 1대 이렇게 셋팅하면
충분히 사용할듯
우리 프로젝트 팀이 4명이니까
한사람 은 db , 한사람은 was , 한사람은 ci 서버
이렇게 분배하면 1년은충분히 돌릴듯?
